---
- hosts: all
  tasks:
    - name: Create user1
      user:
        name: user1
        comment: User 1
        shell: /bin/bash
      become: yes

    - name: Ensure .ssh directory exists.
      file:
        dest: "/home/user1/.ssh"
        mode: 0700
        owner: user1
        state: directory
      become: yes
    - name: Install ssh key
      copy: 
        src: "/home/otr/.ansible/playbooks/6.5.1/key/id_rsa" 
        dest: "/home/user1/.ssh/id_rsa"
        mode: 0600
        owner: user1
      become: yes
    - name: Install ssh pub key
      copy: 
        src: "/home/otr/.ansible/playbooks/6.5.1/key/id_rsa.pub" 
        dest: "/home/user1/.ssh/id_rsa.pub"
        mode: 0600
        owner: user1
      become: yes
