---
- name: Set port
  lineinfile:
    dest: /etc/dnsmasq.conf
    regexp: ^port=
    line: port=53
  become: yes
- name: Disable forward plain names
  lineinfile:
    dest: /etc/dnsmasq.conf 
    regexp: ^domain-needed
    line: domain-needed
  become: yes
- name: Disable forward addresses in non-route spaces
  lineinfile:
    dest: /etc/dnsmasq.conf
    regexp: ^bogus-priv
    line: bogus-priv
  become: yes
- name: Enable dnsmasq to try each query with  each  server  strictly  in  the  order
  lineinfile:
    dest: /etc/dnsmasq.conf
    regexp: ^strict-order
    line: strict-order
  become: yes
- name: Enable automatically added to simple names in a hosts-file
  lineinfile:
    dest: /etc/dnsmasq.conf
    regexp: ^expand-hosts
    line: expand-hosts
  become: yes
- name: Set domain name
  lineinfile:
    dest: /etc/dnsmasq.conf
    regexp: ^domain=
    line: domain=my-domain.com
  become: yes
- name: Set listen address
  lineinfile:
    dest: /etc/dnsmasq.conf
    regexp: ^listen-address=
    line: listen-address=127.0.0.1
  become: yes
